

.PHONY:0060
0060:
	go test -v --test.run=TestPluseOneL1
	go test -v --test.run=TestPluseOneL2

.PHONY:0070
0070:
	go test -v --test.run=TestClimbStairs

.PHONY:0283
0283:
	go test -v --test.run=TestMoveZeros
